apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{app}}-deployment
  namespace: {{app}}
  labels:
    app: {{app}}
spec:
  replicas: {{replicas}}
  selector:
    matchLabels:
      app: {{app}}
  template:
    metadata:
      labels:
        app: {{app}}
    spec:
      containers:
      - name: {{app}}
        image: {{image}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{port}}
        resources:
          limits:
            cpu: {{cpu}}
            memory: {{memory}}
